# This is a basic workflow to help you get started with Actions

name: Ceck Data Commit

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "exec02*" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Verifica data de commit
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          DEADLINE='2023-11-03T14:50:00Z'
          for COMMIT in $(git -rev-list --all --after="$DEADLINE")
          do
          echo "Commit $COMMIT foi feito após o prazo final de entrega da atividade EXEC-02"
          exit 1
          done
          echo "Commit registrado dentro do prazo de entrega $DEADLINE" 
